### ISSUE TITLE
please make change to grab course certificate link & save them as text for all not ready courses (start from my courses tab)

### ISSUE THREAD

**Issue by bugbounted** [pacoDevelop/complete_course_automatically_script_udemy#1]
Hi [pacoDevelop](https://github.com/pacoDevelop),
please make change to grab course certificate link & save them as text for all not ready cerificate courses (start from my courses tab).
all courses not completed are not have active ecrtificate link at the end of course page.
waiting for your response
finest regards

**Comment by pacoDevelop** [comment]
The certificate link is generated when the course is finished, it is impossible to access the link without finishing the course.
